### ISSUE TITLE
Slow performance after install

### ISSUE THREAD

**Issue by b3nsh4** [ElderDrivers/EdXposedManager#141]
Reporting this issue after thorough study of performance after installing EdXposed via magisk. Device has become 'uselessly lagging'. Checked Available memory, seems memory, CPU, and swap everything are fine. Still, I cannot understand what causes EdX making problem. Maybe 'zygote' is lazy loading apps quickly because of injection made by riru? 
Installed modules: Adblocker reborn and Deep screen oreo.

I was able to see people reporting same issue. This problem really needs deep study.
Any suggestion is really appreciated.

**Comment by mario0318** [comment]
As far as I've known and used xposed framework and now edxposed, the framework will simply cause lag in general regardless of how few mods you have active. I believe, and this is simply a guess based on the android boot process and how ed/xposed hooks into the system, it might have to do with how the system's java classes and how they're compiled can't be as speedy as the system would otherwise set up without the framework installed since the framework requires all of those system and app classes to remain accessible for modification to happen. So in general there would be a slight increase in CPU and RAM usage as the framework enforces recompiling the apps or their associated classes at runtime. This got me thinking if it would be a better idea to enable the app blacklist option in edX manager, set it as whitelist and enable only the apps you wish to modify. But unfortunately that would break a couple of system-wide modules that I wish to keep so I've tolerated the lagginess since.

**Comment by b3nsh4** [comment]
> As far as I've known and used xposed framework and now edxposed, the framework will simply cause lag in general regardless of how few mods you have active. I believe, and this is simply a guess based on the android boot process and how ed/xposed hooks into the system, it might have to do with how the system's java classes and how they're compiled can't be as speedy as the system would otherwise set up without the framework installed since the framework requires all of those system and app classes to remain accessible for modification to happen. So in general there would be a slight increase in CPU and RAM usage as the framework enforces recompiling the apps or their associated classes at runtime. This got me thinking if it would be a better idea to enable the app blacklist option in edX manager, set it as whitelist and enable only the apps you wish to modify. But unfortunately that would break a couple of system-wide modules that I wish to keep so I've tolerated the lagginess since. 

Nice thinking. What I thought was, zygote is the one doing app launching. To install  edX, we need 'Riru' installed via magisk. FROM their doc; 

_"Riru only does one thing, inject into zygote in order to allow modules run their codes in apps or the system server"_.

I believe riru causes the problem why app launching is taking too much time. For me, just to load up message, contacts, phone apps -- it takes 4-6 seconds. And each function inside it also buggy!

**Comment by LuigiVampa92** [comment]
I personally haven't noticed any significant overhead using EdXposed on different devices. Could that happen because of AdBlock module? I haven't used it myself but my guess that it causes EdXposed to hook very often (probably on each network connection attempt) and do quite a big job (scan url for match with database), or it could also be a problem in the implementation of that module. It's a blind guess though, but I would try to disable all xposed modules and see if device still suffers performance issues

**Comment by b3nsh4** [comment]
> I personally haven't noticed any significant overhead using EdXposed on different devices. Could that happen because of AdBlock module? I haven't used it myself but my guess that it causes EdXposed to hook very often (probably on each network connection attempt) and do quite a big job (scan url for match with database), or it could also be a problem in the implementation of that module. It's a blind guess though, but I would try to disable all xposed modules and see if device still suffers performance issues

Forgot to mention, Uninstalled all modules and watched performance. No noticeable differences

**Comment by mario0318** [comment]
The only thing I could suggest that has worked for me and others is to edit the build property for the following props:

**dalvik.vm.dex2oat-filter**
**dalvik.vm.image-dex2oat-filter**

Then you can change either one or both properties to use the filter **everything**
It may be set by default to speed, quicken, balanced, interpret-only. Some people report switching from one to another then clearing dalvik-cache and reboot seems to give a noticeable performance boost with app launch time, boot time, or gaining more internal storage memory from slimmer apps. Generally the filter set to **everything** seems to be the most noticeable, followed with filter **balanced**, then **speed**, then **interpret-only** 

**Warning...**every device is different and not every device will boot without a potential bootloop, so be warned!!!
