### ISSUE TITLE
Add a new Meta "Required in Whitelist" for edxposed modules.

### ISSUE THREAD

**Issue by NULL0B** [ElderDrivers/EdXposedManager#168]
Hello as EdXposed 5 certainly requires whitelist enabled due performance issues. It would be great to add a new Meta in manifest containing the packages that are required in whitelist. EdXposed Manager could check that and warn the user. Or maybe the framework could dynamically add it to the list and warn the user for next reboot or something. Besides this is related to framework and manager decided to open this issue here insead. Thanks

**Comment by wildanie** [comment]
I think it's time EdXposed to scramble the package names

**Comment by wildanie** [comment]
I think it's time EdXposed to scramble the package names

**Comment by blackbox87** [comment]
After updating I imminently noticed that EdXposed was slowing things down. And I'm using a Poco F1, which is still going strong in 2021.

I 100% agree with the suggestion. Whitelist mode should be enabled by default and modules should be able to define what apps they need to hook via the manifest. It really helps to mitigate the slowdowns caused by the EdXposed changes.

**Comment by NULL0B** [comment]
is a valid way that when the edxposed framwork tries to hook an app and fails because is not whitelisted the framwork indicates via manager hooks detected that are not whitelisted and required?
this could make it backwards compatible with the modules.

**Comment by MlgmXyysd** [comment]
https://github.com/ElderDrivers/EdXposedManager/commit/17b816da08f975e668809bc6786b16b0b7db32df
