### ISSUE TITLE
Unable to install 'Riru-Edxposed' in Magisk.

### ISSUE THREAD

**Issue by FridayAnubis** [ElderDrivers/EdXposedManager#216]
###### Include the following:
 - EdXposed Version: `v0.5.2.2_4683-master`
 - Android Version: `11`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi9`
 - EdXposed Manager Version: `4.6.2`
 
###### Reproduction Steps

1. Enable ’Riru' module in Magisk.
2. Reboot.
3. Install 'Riru-Edxposed' module in Magisk.

###### Expected Result

The 'Riru-Edxposed' is successfully installed.

###### Actual Result

It shows that Riru hasn't been installed, installation failed.

**Comment by YuMore233** [comment]
Due to the low quality of Riru's documentation and the high frequency of API changes, the development team has decided not to adapt Riru 26 for the time being. Please wait for the development team member solohsu for the subsequent maintenance plan. We deeply regret this irresponsible change of Riru.

Please do NOT update to Riru 26, we recommend using a version below 25. The last available version is 25.4.4: https://t.me/EdXposed/136
